on:
    push:
        branches:
            - dev
    workflow_dispatch:

jobs:
    call-workflow-passing-data:
        uses: ./.github/workflows/build_and_deploy.yml
        with:
            environment: staging
        secrets: inherit
