on:
    push:
        branches:
            - release-*

jobs:
    call-workflow-passing-data:
        uses: ./.github/workflows/build_and_deploy.yml
        with:
            environment: production
        secrets: inherit
